gui:
  scrollHeight: 2
  language: "zh-CN"
  timeFormat: 2006-01-02 15:04:05
  shortTimeFormat: 15:04
  nerdFontsVersion: "3"
  sidePanelWidth: 0.2
  showBranchCommitHash: true
  splitDiff: "auto"

git:
  pagers:
    - pager: delta --paging=never
  log:
    showWholeGraph: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

keybinding:
  universal:
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextTab: <tab>
    prevTab: <backtab>
